package imperium.enums;
public enum FoodType { WILD_BOAR, PASSABLE_FISH, STALE_FISH, LOBSTER, STRAWBERRIES, CARROTS, FRESH_CLOVER, STALE_CLOVER, HONEY, WINE, MEAD, BEET_JUICE, MISTLETOE, SALT, ROCK_OIL, UNICORN_MILK, IDEFIX_HAIR, SECRET_INGREDIENT }
